# Use a Python 3.11 base image for x86 architecture
FROM python:3.11-slim-bullseye AS base

# Set working directory inside the container
WORKDIR /app

# Copy requirements and install them
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy your application code
COPY ./app /app/app

# Expose the port that Uvicorn will use
EXPOSE 8080

# Define the command to run the application
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]